plugins {
    java
    `maven-publish`
}

allprojects {
    apply<JavaPlugin>()

    group = "net.hypejet"
    version = "1.0-SNAPSHOT"

    repositories {
        mavenCentral()
    }

    java {
        withJavadocJar()
        withSourcesJar()
        toolchain.languageVersion.set(JavaLanguageVersion.of(21))
    }
}

val subprojectsToCompile = sequenceOf(
    project(":model"),
    project(":autogenerated")
)

dependencies {
    compileOnly(libs.adventureApi)
    compileOnly(libs.checkerFrameworkQual)
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks {
    jar {
        dependsOn(project(":generator").tasks.named("runShadow"))
        subprojectsToCompile.forEach { from(it.sourceSets.main.get().output) }
    }
    javadoc {
        subprojectsToCompile.forEach { source(it.sourceSets.main.get().allSource) }
    }
    named<Jar>("sourcesJar") {
        subprojectsToCompile.forEach { from(it.sourceSets.main.get().allSource) }
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }
}