rootProject.name = "jet-data-parent"

pluginManagement {
    repositories {
        maven("https://repo.spongepowered.org/repository/maven-public/")
    }
}

sequenceOf("model", "generator", "autogenerated-api", "autogenerated-server", "codecs").forEach {
    include("jet-data-$it")
    project(":jet-data-$it").projectDir = file(it)
}
