package net.hypejet.jet.data.generator.generators;

import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.FieldSpec;
import net.hypejet.jet.data.generator.ConstantGenerator;
import net.hypejet.jet.data.generator.Generator;
import net.hypejet.jet.data.generator.util.CodeBlocks;
import net.hypejet.jet.data.generator.util.JavaDocBuilder;
import net.hypejet.jet.data.generator.util.ResourceLocationUtil;
import net.minecraft.core.DefaultedRegistry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.EntityType;
import org.checkerframework.checker.nullness.qual.NonNull;
import org.slf4j.Logger;

import javax.lang.model.element.Modifier;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

/**
 * Represents a {@linkplain ConstantGenerator constant generator}, which
 * generates {@linkplain net.hypejet.jet.data.entity.type.EntityType entity types} using data defined in
 * an {@linkplain BuiltInRegistries#ENTITY_TYPE entity type registry}.
 *
 * @since 1.0
 * @author Codestech
 * @see net.hypejet.jet.data.entity.type.EntityType
 * @see BuiltInRegistries#ENTITY_TYPE
 * @see Generator
 */
public final class VanillaEntityTypeGenerator extends ConstantGenerator {

    private static final String PACKAGE = "net.hypejet.jet.data.entity.type";
    private static final String CLASS_NAME = "VanillaEntityTypes";

    private static final Class<?> ENTITY_TYPE_CLASS = net.hypejet.jet.data.entity.type.EntityType.class;

    /**
     * Constructs the {@linkplain VanillaEntityTypeGenerator vanilla entity type generator}.
     *
     * @since 1.0
     */
    public VanillaEntityTypeGenerator() {
        super(PACKAGE, ClassName.get(PACKAGE, CLASS_NAME), ENTITY_TYPE_CLASS,
                JavaDocBuilder.builder()
                        .line("Represents a built-in Minecraft entity type.")
                        .paragraph("Code autogenerated, do not edit!")
                        .emptyLine()
                        .since("1.0")
                        .see(ENTITY_TYPE_CLASS)
                        .build(),
                JavaDocBuilder.builder()
                        .line("Gets all built-in entity types.")
                        .emptyLine()
                        .returns("the blocks")
                        .since("1.0")
                        .see(ENTITY_TYPE_CLASS)
                        .build());
    }

    @Override
    public @NonNull Collection<FieldSpec> generateFields(@NonNull Logger logger) {
        DefaultedRegistry<EntityType<?>> registry = BuiltInRegistries.ENTITY_TYPE;
        ClassName entityTypeImplClassName = ClassName.get(PACKAGE, "EntityTypeImpl");

        List<FieldSpec> entityTypeFieldSpecs = new ArrayList<>();

        for (EntityType<?> entityType : registry) {
            ResourceLocation location = ResourceLocationUtil.getOrThrow(registry, entityType);
            entityTypeFieldSpecs.add(FieldSpec.builder(ENTITY_TYPE_CLASS, location.getPath().toUpperCase())
                    .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                    .initializer(CodeBlocks.constructor(entityTypeImplClassName,
                            CodeBlocks.keyCreator(location),
                            registry.getId(entityType)))
                    .build());
        }

        return List.copyOf(entityTypeFieldSpecs);
    }
}